"""Tests to ensure the Alembic migration chain stays in sync with models."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest


def _run_cmd(
    cmd: list[str], cwd: Path, env: dict[str, str] | None = None
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
        env=env,
    )


@pytest.mark.integration
def test_alembic_migration_is_up_to_date() -> None:
    """Ensure the Alembic schema matches the current SQLAlchemy models.

    This prevents the database schema and the application models from
    silently drifting. If the models have changed but the migration has not
    been autogenerated, ``alembic check`` will exit with a non-zero status
    and the test fails.
    """
    repo_root = Path(__file__).resolve().parents[3]
    backend_dir = repo_root / "backend"
    db_path = backend_dir / "_alembic_check.db"
    if db_path.exists():
        db_path.unlink()
    env = os.environ.copy()
    env["DATABASE_URL"] = f"sqlite+aiosqlite:///{db_path}"
    try:
        _run_cmd([sys.executable, "-m", "alembic", "upgrade", "head"], backend_dir, env)
        _run_cmd([sys.executable, "-m", "alembic", "check"], backend_dir, env)
    finally:
        if db_path.exists():
            db_path.unlink()
