"""initial schema

Revision ID: e9103eb4c7c4
Revises: 
Create Date: 2026-10-01 13:28:22.870239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e9103eb4c7c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_reference', sa.String(length=64), nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('reported_address', sa.String(length=128), nullable=False),
    sa.Column('reported_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_date_precision', sa.String(length=32), nullable=False),
    sa.Column('reported_amount', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('reported_asset', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('data_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('code_version', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('analysis_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_reference'), 'cases', ['case_reference'], unique=True)
    op.create_index(op.f('ix_cases_reported_address'), 'cases', ['reported_address'], unique=False)
    op.create_table('entity_labels',
    sa.Column('entity_name', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=True),
    sa.Column('label_origin', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=512), nullable=False),
    sa.Column('verification_level', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=True),
    sa.Column('last_verified_at', sa.Date(), nullable=True),
    sa.Column('scope_notes', sa.String(length=512), nullable=True),
    sa.Column('is_shared_infrastructure', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'address', 'source_name', name='uq_entity_labels_addr_source')
    )
    op.create_index(op.f('ix_entity_labels_address'), 'entity_labels', ['address'], unique=False)
    op.create_table('transactions',
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('transfer_kind', sa.String(length=16), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sender', sa.String(length=128), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('asset_id', sa.String(length=128), nullable=False),
    sa.Column('asset_symbol', sa.String(length=32), nullable=False),
    sa.Column('asset_decimals', sa.Integer(), nullable=True),
    sa.Column('amount_raw', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('amount_decimal', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'tx_hash', 'log_index', 'transfer_kind', 'sender', 'receiver', 'asset_id', name='uq_transactions_event')
    )
    op.create_index('ix_transactions_receiver_time', 'transactions', ['receiver', 'block_timestamp'], unique=False)
    op.create_index('ix_transactions_sender_time', 'transactions', ['sender', 'block_timestamp'], unique=False)
    op.create_index('ix_transactions_tx_hash', 'transactions', ['tx_hash'], unique=False)
    op.create_table('audit_events',
    sa.Column('case_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_case_time', 'audit_events', ['case_id', 'occurred_at'], unique=False)
    op.create_table('case_links',
    sa.Column('case_a_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('case_b_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('strength', sa.String(length=32), nullable=False),
    sa.Column('evidence_tag', sa.String(length=32), nullable=False),
    sa.Column('shared_addresses', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('shared_transactions', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('shared_path_segments', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('shared_infrastructure_flag', sa.Boolean(), nullable=False),
    sa.Column('temporal_notes', sa.String(length=512), nullable=True),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_history', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_a_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_b_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_a_id', 'case_b_id', name='uq_case_links_ab')
    )
    op.create_table('case_paths',
    sa.Column('case_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('path_index', sa.Integer(), nullable=False),
    sa.Column('hop_count', sa.Integer(), nullable=False),
    sa.Column('start_address', sa.String(length=128), nullable=False),
    sa.Column('end_address', sa.String(length=128), nullable=False),
    sa.Column('first_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=False),
    sa.Column('traced_value_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('traced_value_asset', sa.String(length=32), nullable=False),
    sa.Column('tracing_method', sa.String(length=32), nullable=False),
    sa.Column('value_continuity_ratio', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('relevance_criteria', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('has_break', sa.Boolean(), nullable=False),
    sa.Column('break_reason', sa.String(length=64), nullable=True),
    sa.Column('edges', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_private_details',
    sa.Column('case_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('narrative_ciphertext', sa.String(length=8192), nullable=True),
    sa.Column('contact_ciphertext', sa.String(length=1024), nullable=True),
    sa.Column('consent_recorded', sa.Boolean(), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('case_transactions',
    sa.Column('case_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('transaction_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('hop_depth', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('included_reason', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label_change_log',
    sa.Column('label_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.String(length=128), nullable=False),
    sa.Column('previous_value', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['entity_labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('case_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_reference', sa.String(length=512), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_case_id', 'reports', ['case_id'], unique=False)
    op.create_table('case_attributions',
    sa.Column('case_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('path_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('label_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('connection_type', sa.String(length=32), nullable=False),
    sa.Column('attribution_state', sa.String(length=64), nullable=False),
    sa.Column('attribution_confidence_level', sa.String(length=32), nullable=False),
    sa.Column('confidence_factors', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('label_is_stale', sa.Boolean(), nullable=False),
    sa.Column('shared_infrastructure_flag', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['entity_labels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['path_id'], ['case_paths.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_signals',
    sa.Column('case_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('path_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('signal_key', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('evidence_tag', sa.String(length=32), nullable=False),
    sa.Column('feature_values', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.String(length=1024), nullable=False),
    sa.Column('limitation_note', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['case_paths.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_signals')
    op.drop_table('case_attributions')
    op.drop_index('ix_reports_case_id', table_name='reports')
    op.drop_table('reports')
    op.drop_table('label_change_log')
    op.drop_table('case_transactions')
    op.drop_table('case_private_details')
    op.drop_table('case_paths')
    op.drop_table('case_links')
    op.drop_index('ix_audit_events_case_time', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_transactions_tx_hash', table_name='transactions')
    op.drop_index('ix_transactions_sender_time', table_name='transactions')
    op.drop_index('ix_transactions_receiver_time', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_entity_labels_address'), table_name='entity_labels')
    op.drop_table('entity_labels')
    op.drop_index(op.f('ix_cases_reported_address'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_reference'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
